// Here is a list of the toolbar
// Detail list see https://www.tinymce.com/docs/advanced/editor-control-identifiers/#toolbarcontrols

const attribute = [
  'color',
  'text', // 需要特殊处理
  'width',
  'widthType',
  'interval',
  'intervalAfter',
  'src',
  'marginLeft',
  'marginRight',
  'marginTop',
  'marginBottom',
  'lineHeight',
  'border',
  'box_shadow',
  'border_radius',
  '_webkit_box_reflect',
  '_webkit_mask',
  'filter',
  'borderType',
  'borderSize',
  'radius',
  'borderTopType',
  'borderColor',
  'radiusType',
  'radiusTop',
  'radiusTopType',
  'borderRightType',
  'borderRightSize',
  'borderRightColor',
  'radiusRight',
  'radiusRightType',
  'borderBottomType',
  'borderBottomSize',
  'borderBottomColor',
  'radiusBottom',
  'radiusBottomType',
  'borderLeftType',
  'borderLeftSize',
  'borderLeftColor',
  'radiusLeft',
  'radiusLeftType',
  'height',
  'letterSpacing',
  'align',
  'backgroundColor',
  'zoom',
  'opacity',
  'rotate',
  'rotateType',
  'isReflect',
  'reflectSpace',
  'reflectOpacity',
  'textAlign'
]

export default attribute
